test: match gccgo error messages for bug388.go
As runtime.UintType is no longer defined, the gccgo error
messages have changed.

bug388.go:12:10: error: reference to undefined identifier ?runtime.UintType?
bug388.go:12:10: error: invalid named/anonymous mix
bug388.go:13:21: error: reference to undefined identifier ?runtime.UintType?
bug388.go:17:10: error: reference to undefined identifier ?runtime.UintType?
bug388.go:18:18: error: reference to undefined identifier ?runtime.UintType?
bug388.go:22:9: error: non-name on left side of ?:=?
bug388.go:27:10: error: expected type
bug388.go:32:9: error: expected type
bug388.go:23:14: error: reference to field ?i? in object which has no fields or methods

R=golang-dev, gri
CC=golang-dev
http://codereview.appspot.com/5755044